### PR TITLE
[P1] Plichta, Wasielewska, Kubacki

### PR DESCRIPTION
**Pull request by Weronika375**
Submission project1 AML

### CODE REVIEW

**Comment by kozaka93** [comment]
Your file `diabetes.csv` is out of the directory `Surname1_Surname2_Surname3`.

**Comment by Weronika375** [comment]
Corrected

**Comment by kozaka93** [comment]
Please, reorganize the directory adding required code folder.

**Comment by Weronika375** [comment]
Done.

**Pull request merged**
